version: "3.6"
services:
  frontend:
    build: frontend
    ports:
      - 8080:80
    depends_on:
      - backend
  backend:
    build: backend
  postgres:
    image: postgres:latest
    container_name: chef_postgres_db
    environment:
      POSTGRES_DB: homechef
      POSTGRES_USER: malik
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
